--Creating Schema
--Dimension tables

CREATE TABLE dim_date (
    date_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    full_date   DATE,
    year_num    NUMBER,
    month_num   NUMBER,
    month_name  VARCHAR2(20),
    quarter_num NUMBER,
    day_num     NUMBER,
    week_num    NUMBER
);

CREATE TABLE dim_location (
    location_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    state       VARCHAR2(100),
    city        VARCHAR2(100),
    location    VARCHAR2(200)
);

CREATE TABLE dim_restaurant (
    restaurant_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    restaurant_name VARCHAR2(200)
);

CREATE TABLE dim_category (
    category_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    category    VARCHAR2(200)
);

CREATE TABLE dim_dish (
    dish_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    dish_name VARCHAR2(200)
);

--Fact Table
CREATE TABLE fact_foodie_orders (
    order_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    date_id       NUMBER,
    price_npr     NUMBER(10, 2),
    rating        NUMBER(4, 2),
    rating_count  NUMBER,
    location_id   NUMBER,
    restaurant_id NUMBER,
    category_id   NUMBER,
    dish_id       NUMBER,
    CONSTRAINT fk_date FOREIGN KEY ( date_id )
        REFERENCES dim_date ( date_id ),
    CONSTRAINT fk_location FOREIGN KEY ( location_id )
        REFERENCES dim_location ( location_id ),
    CONSTRAINT fk_restaurant FOREIGN KEY ( restaurant_id )
        REFERENCES dim_restaurant ( restaurant_id ),
    CONSTRAINT fk_category FOREIGN KEY ( category_id )
        REFERENCES dim_category ( category_id ),
    CONSTRAINT fk_dish FOREIGN KEY ( dish_id )
        REFERENCES dim_dish ( dish_id )
);