UPDATE foodie_raw
SET
    order_date_clean =
        CASE
            WHEN order_date LIKE '%/%' THEN
                TO_DATE(order_date, 'DD/MM/YYYY')
            ELSE
                TO_DATE(order_date, 'DD-MM-YYYY')
        END;

SELECT
    *
FROM
    foodie_raw;

--Data validation and cleaning
SELECT
    SUM(
        CASE
            WHEN state IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_state,
    SUM(
        CASE
            WHEN city IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_city,
    SUM(
        CASE
            WHEN restaurant_name IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_restaurant,
    SUM(
        CASE
            WHEN location IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_location,
    SUM(
        CASE
            WHEN category IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_category,
    SUM(
        CASE
            WHEN dish_name IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_dish,
    SUM(
        CASE
            WHEN price_npr IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_price,
    SUM(
        CASE
            WHEN rating IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_rating,
    SUM(
        CASE
            WHEN rating_count IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_ratingcount,
    SUM(
        CASE
            WHEN order_date IS NULL THEN
                1
            ELSE
                0
        END
    ) AS null_orderdate
FROM
    foodie_raw;

--NVL Function for null values
SELECT
    nvl(state, 'Unknown')           AS state,
    nvl(city, 'Unknown')            AS city,
    nvl(restaurant_name, 'Unknown') AS restaurant_name,
    nvl(location, 'Unknown')        AS location,
    nvl(category, 'Unknown')        AS category,
    nvl(dish_name, 'Unknown')       AS dish_name,
    nvl(price_npr, 0)               AS price_npr,
    nvl(rating, 0)                  AS rating,
    nvl(rating_count, 0)            AS rating_count,
    order_date
FROM
    foodie_raw;

--Blank or Empty Strings
SELECT
    *
FROM
    foodie_raw
WHERE
    state = ''
    OR city = ''
    OR restaurant_name = ''
    OR location = ''
    OR category = ''
    OR dish_name = ''
    OR order_date = '';

--Duplicate Data
SELECT
    state,
    city,
    restaurant_name,
    location,
    category,
    dish_name,
    price_npr,
    rating,
    rating_count,
    order_date,
    COUNT(*) AS count
FROM
    foodie_raw
GROUP BY
    state,
    city,
    restaurant_name,
    location,
    category,
    dish_name,
    price_npr,
    rating,
    rating_count,
    order_date
HAVING
    COUNT(*) > 1;

-- Delete duplicate data
DELETE FROM foodie_raw
WHERE
    ROWID IN (
        SELECT
            rid
        FROM
            (
                SELECT
                    ROWID AS rid, ROW_NUMBER()
                                  OVER(PARTITION BY state, city, restaurant_name, order_date, location,
                                                    category, rating, rating_count, dish_name, price_npr
                                       ORDER BY
                                           ROWID
                    )     AS rn
                FROM
                    foodie_raw
            )
        WHERE
            rn > 1
    );

--Creating Schema
--Dimension tables

CREATE TABLE dim_date (
    date_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    full_date   DATE,
    year_num    NUMBER,
    month_num   NUMBER,
    month_name  VARCHAR2(20),
    quarter_num NUMBER,
    day_num     NUMBER,
    week_num    NUMBER
);

CREATE TABLE dim_location (
    location_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    state       VARCHAR2(100),
    city        VARCHAR2(100),
    location    VARCHAR2(200)
);

CREATE TABLE dim_restaurant (
    restaurant_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    restaurant_name VARCHAR2(200)
);

CREATE TABLE dim_category (
    category_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    category    VARCHAR2(200)
);

CREATE TABLE dim_dish (
    dish_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    dish_name VARCHAR2(200)
);

--Fact Table
CREATE TABLE fact_foodie_orders (
    order_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    date_id       NUMBER,
    price_npr     NUMBER(10, 2),
    rating        NUMBER(4, 2),
    rating_count  NUMBER,
    location_id   NUMBER,
    restaurant_id NUMBER,
    category_id   NUMBER,
    dish_id       NUMBER,
    CONSTRAINT fk_date FOREIGN KEY ( date_id )
        REFERENCES dim_date ( date_id ),
    CONSTRAINT fk_location FOREIGN KEY ( location_id )
        REFERENCES dim_location ( location_id ),
    CONSTRAINT fk_restaurant FOREIGN KEY ( restaurant_id )
        REFERENCES dim_restaurant ( restaurant_id ),
    CONSTRAINT fk_category FOREIGN KEY ( category_id )
        REFERENCES dim_category ( category_id ),
    CONSTRAINT fk_dish FOREIGN KEY ( dish_id )
        REFERENCES dim_dish ( dish_id )
);

--Data insertion
INSERT INTO dim_date (
    full_date,
    year_num,
    month_num,
    month_name,
    quarter_num,
    day_num,
    week_num
)
    SELECT DISTINCT
        order_date,
        EXTRACT(YEAR FROM order_date),
        EXTRACT(MONTH FROM order_date),
        rtrim(to_char(order_date, 'Month')),
        TO_NUMBER(to_char(order_date, 'Q')),
        EXTRACT(DAY FROM order_date),
        TO_NUMBER(to_char(order_date, 'IW'))
    FROM
        foodie_raw
    WHERE
        order_date IS NOT NULL;

INSERT INTO dim_location (
    state,
    city,
    location
)
    SELECT DISTINCT
        state,
        city,
        location
    FROM
        foodie_raw
    WHERE
        state IS NOT NULL
        AND city IS NOT NULL
        AND location IS NOT NULL;

INSERT INTO dim_restaurant ( restaurant_name )
    SELECT DISTINCT
        restaurant_name
    FROM
        foodie_raw
    WHERE
        restaurant_name IS NOT NULL;

INSERT INTO dim_category ( category )
    SELECT DISTINCT
        category
    FROM
        foodie_raw
    WHERE
        category IS NOT NULL;

INSERT INTO dim_dish ( dish_name )
    SELECT DISTINCT
        dish_name
    FROM
        foodie_raw
    WHERE
        dish_name IS NOT NULL;

INSERT INTO fact_foodie_orders (
    date_id,
    price_npr,
    rating,
    rating_count,
    location_id,
    restaurant_id,
    category_id,
    dish_id
)
    SELECT
        dd.date_id,
        f.price_npr,
        f.rating,
        f.rating_count,
        dl.location_id,
        dr.restaurant_id,
        dc.category_id,
        dsh.dish_id
    FROM
             foodie_raw f
        JOIN dim_date       dd ON dd.full_date = f.order_date
        JOIN dim_location   dl ON dl.state = f.state
                                AND dl.city = f.city
                                AND dl.location = f.location
        JOIN dim_restaurant dr ON dr.restaurant_name = f.restaurant_name
        JOIN dim_category   dc ON dc.category = f.category
        JOIN dim_dish       dsh ON dsh.dish_name = f.dish_name;

SELECT
    *
FROM
    fact_foodie_orders;

--Full Schema
SELECT
    *
FROM
         fact_foodie_orders f
    JOIN dim_date       d ON d.date_id = f.date_id
    JOIN dim_location   l ON l.location_id = f.location_id
    JOIN dim_restaurant r ON r.restaurant_id = f.restaurant_id
    JOIN dim_category   c ON c.category_id = f.category_id
    JOIN dim_dish       dsh ON dsh.dish_id = f.dish_id;


--KPI's
--Total Orders
SELECT
    COUNT(*) AS total_orders
FROM
    fact_foodie_orders;

SELECT
    *
FROM
    fact_foodie_orders;

--Total Revenue (NPR Million)
SELECT
    round(sum(price_npr) / 1000000,
          2)
    || ' NPR Million' AS total_revenue
FROM
    fact_foodie_orders;

--Average Dish Price
SELECT
    round(
        avg(price_npr),
        2
    )
    || ' NPR' AS average_price
FROM
    fact_foodie_orders;

--Average Rating
SELECT
    round(
        avg(rating),
        2
    )
FROM
    fact_foodie_orders;

--Deep Dive Business Analysis

--Monthly trend
SELECT
    d.year_num,
    d.month_num,
    d.month_name,
    COUNT(*) AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_date d ON f.date_id = d.date_id
GROUP BY
    d.year_num,
    d.month_num,
    d.month_name
ORDER BY
    COUNT(*) DESC;

--Quaterly Trend
SELECT
    d.year_num,
    d.quarter_num,
    COUNT(*) AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_date d ON f.date_id = d.date_id
GROUP BY
    d.year_num,
    d.quarter_num
ORDER BY
    COUNT(*) DESC;

--Yearly Trend
SELECT
    d.year_num,
    COUNT(*) AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_date d ON f.date_id = d.date_id
GROUP BY
    d.year_num
ORDER BY
    COUNT(*) DESC;

--Orders by Day of week 
SELECT
    to_char(d.full_date, 'Day') AS day_name,
    COUNT(*)                    AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_date d ON f.date_id = d.date_id
GROUP BY
    to_char(d.full_date, 'Day'),
    to_char(d.full_date, 'D')
ORDER BY
    to_char(d.full_date, 'D');
    
--Top 10 cities by order volume
SELECT
    l.city,
    COUNT(*) AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_location l ON l.location_id = f.location_id
GROUP BY
    l.city
ORDER BY
    COUNT(*) DESC
FETCH FIRST 10 ROWS ONLY;

--Revenue contribution by states
SELECT
    l.state,
    SUM(f.price_npr) AS total_revenue
FROM
         fact_foodie_orders f
    JOIN dim_location l ON l.location_id = f.location_id
GROUP BY
    l.state
ORDER BY
    SUM(f.price_npr) DESC;

--Top 10 restaurants by orders
SELECT
    r.restaurant_name,
    SUM(f.price_npr) AS total_revenue
FROM
         fact_foodie_orders f
    JOIN dim_restaurant r ON r.restaurant_id = f.restaurant_id
GROUP BY
    r.restaurant_name
ORDER BY
    SUM(f.price_npr) DESC;

--Top Categories by order volume
SELECT
    c.category,
    COUNT(*) AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_category c ON c.category_id = f.category_id
GROUP BY
    c.category
ORDER BY
    COUNT(*) DESC;

--Most Ordered Dishes
SELECT
    d.dish_name,
    COUNT(*) AS total_orders
FROM
         fact_foodie_orders f
    JOIN dim_dish d ON d.dish_id = f.dish_id
GROUP BY
    d.dish_name
ORDER BY
    COUNT(*) DESC
FETCH FIRST 10 ROWS ONLY;

--Cuisine Performance (Orders + Avg Rating)
SELECT
    c.category,
    COUNT(*) AS total_orders,
    round(
        avg(f.rating),
        2
    )        AS avg_rating
FROM
         fact_foodie_orders f
    JOIN dim_category c ON f.category_id = c.category_id
GROUP BY
    c.category
ORDER BY
    COUNT(*) DESC;

--Customer Spending Insights
SELECT
    CASE
        WHEN price_npr < 100               THEN
            'under 100'
        WHEN price_npr BETWEEN 100 AND 199 THEN
            '100 - 199'
        WHEN price_npr BETWEEN 200 AND 299 THEN
            '200 - 299'
        WHEN price_npr BETWEEN 300 AND 499 THEN
            '300 - 499'
        ELSE
            '500+'
    END      AS price_range,
    COUNT(*) AS total_orders
FROM
    fact_foodie_orders
GROUP BY
    CASE
        WHEN price_npr < 100               THEN
            'under 100'
        WHEN price_npr BETWEEN 100 AND 199 THEN
            '100 - 199'
        WHEN price_npr BETWEEN 200 AND 299 THEN
            '200 - 299'
        WHEN price_npr BETWEEN 300 AND 499 THEN
            '300 - 499'
        ELSE
            '500+'
    END
ORDER BY
    total_orders DESC;

--Rating COunt Distribution (1-5)
SELECT
    rating,
    COUNT(*) AS rating_count
FROM
    fact_foodie_orders
GROUP BY
    rating
ORDER BY
    rating;